version: 1.0.{build}-{branch}

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -U pip setuptools pycryptodome pyinstaller"
  - "%PYTHON%\\Scripts\\pyinstaller.exe PasswordSaver.spec"