version: 1.3.{build}-{branch}

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -U pip setuptools pycryptodome pyinstaller"

build_script:
  - "%PYTHON%\\Scripts\\pyinstaller.exe PasswordSaver.spec"

artifacts:
  - path: dist/PasswordSaver.exe